const REPORT_TITLES = {
  "daily-sales": "الملخص اليومي للمبيعات",
  "detailed-sales": "المبيعات التفصيلية",
  "sales-by-item": "مبيعات حسب الصنف",
  "sales-by-category": "مبيعات حسب الفئة",
  "sales-by-cashier": "مبيعات حسب الكاشير",
  "sales-by-payment": "مبيعات حسب طريقة الدفع",
  "sales-heatmap": "خريطة كثافة المبيعات",
  "exceptions": "استثناءات المبيعات",
  "period-comparison": "مقارنة الفترات",
  "slow-moving": "الأصناف بطيئة الحركة",
  "stock-levels": "أرصدة المخزون",
  "stock-movements": "حركات المخزون",
  "stock-valuation": "تقييم المخزون",
  "count-sheet": "كشف الجرد",
  "reorder": "إعادة الطلب",
  "expiry": "تواريخ الصلاحية",
  "ar-aging": "أعمار مديونية العملاء",
  "ap-aging": "أعمار مديونية الموردين",
  "profit-loss": "الأرباح والخسائر",
  "cash-flow": "التدفق النقدي",
  "treasury": "الخزائن والبنوك",
  "vat": "ضريبة القيمة المضافة",
  "customer-statement": "كشف حساب عميل",
  "top-customers": "أفضل العملاء",
  "shift-history": "سجل الورديات",
  "audit-log": "سجل التدقيق",
  "gross-net-sales": "إجمالي وصافي المبيعات",
  "sales-returns": "مرتجعات المبيعات",
  "discount-analysis": "تحليل الخصومات",
  "margin-by-item": "هامش الربح حسب الصنف",
  "margin-by-category": "هامش الربح حسب الفئة",
  "purchase-summary": "ملخص المشتريات",
  "detailed-purchases": "المشتريات التفصيلية",
  "purchases-by-supplier": "مشتريات حسب المورد",
  "purchases-by-item": "مشتريات حسب الصنف",
  "purchase-returns": "مرتجعات المشتريات",
  "supplier-pricing": "أسعار الموردين",
  "inventory-aging": "أعمار المخزون",
  "dead-stock": "المخزون الراكد",
  "collection-efficiency": "كفاءة التحصيل",
  "supplier-statement": "كشف حساب مورد",
  "cash-consistency": "مطابقة النقدية",
  "payment-method-flow": "تدفق وسائل الدفع",
  "bank-cash-split": "توزيع الخزائن والبنوك",
  "reconciliation-exceptions": "استثناءات التسوية",
  "output-vat": "ضريبة المخرجات",
  "input-vat": "ضريبة المدخلات",
  "vat-filing-summary": "ملخص الإقرار الضريبي",
  "returns-tax-effect": "الأثر الضريبي للمرتجعات",
  "user-activity": "نشاط المستخدمين",
  "margin-health": "صحة هوامش الربح",
  "sales-returns-summary": "ملخص مرتجعات المبيعات",
  "sales-returns-by-customer": "مرتجعات المبيعات حسب العميل",
  "purchase-returns-summary": "ملخص مرتجعات المشتريات",
  "purchase-returns-by-supplier": "مرتجعات المشتريات حسب المورد",
  "customer-loyalty": "ولاء العملاء",
  "supplier-purchases-history": "سجل مشتريات المورد",
  "supplier-returns-history": "سجل مرتجعات المورد",
  "daily-sessions": "جلسات الخزينة اليومية",
  "withdrawals-report": "تقرير السحوبات",
  "expense-summary": "ملخص المصروفات",
  "detailed-expenses": "المصروفات التفصيلية",
  "expenses-by-category": "المصروفات حسب الفئة",
  "expenses-by-payment": "المصروفات حسب طريقة الدفع",
  "revenue-summary": "ملخص الإيرادات",
  "detailed-revenues": "الإيرادات التفصيلية",
  "revenues-by-category": "الإيرادات حسب الفئة",
  "revenues-by-payment": "الإيرادات حسب طريقة الدفع",
  "cheque-listing": "كشف الشيكات",
  "bank-transactions": "حركات البنوك",
  "bank-summary": "ملخص البنوك",
  "installment-plans": "خطط التقسيط",
  "installment-collections": "تحصيلات التقسيط",
  "installments-by-customer": "التقسيط حسب العميل",
  "installment-delinquent": "المتأخرات التقسيط",
  "branch-transfers": "التحويلات بين الفروع",
  "warehouse-levels": "أرصدة المخازن",
  "warehouse-levels-summary": "ملخص أرصدة المخازن",
  "employee-adjustments": "حوافز الموظفين",
  "user-list": "قائمة المستخدمين",
  "user-performance": "أداء المستخدمين",
  "login-history": "سجل تسجيل الدخول",
  "profit-by-category": "الربح حسب الفئة",
  "profit-by-customer": "الربح حسب العميل",
  "profit-by-period": "الربح حسب الفترة",
};

const AR_LABELS = {
  id: "المعرف",
  item_code: "كود الصنف",
  code: "الكود",
  sku: "SKU",
  barcode: "الباركود",
  item_id: "معرف الصنف",
  item_name: "اسم الصنف",
  name: "الاسم",
  invoice_no: "رقم الفاتورة",
  doc_no: "رقم المستند",
  purchase_no: "رقم الشراء",
  ref_no: "رقم المرجع",
  return_ref: "رقم المرتجع",
  customer_name: "العميل",
  supplier_name: "المورد",
  cashier: "الكاشير",
  handled_by: "تم بواسطة",
  created_by: "أنشئ بواسطة",
  full_name: "المستخدم",
  phone: "الهاتف",
  date: "التاريخ",
  created_at: "تاريخ الإنشاء",
  opened_date: "تاريخ الفتح",
  closed_at: "تاريخ الإغلاق",
  purchase_date: "تاريخ الشراء",
  last_purchase_date: "آخر تاريخ شراء",
  last_invoice_date: "آخر فاتورة",
  last_sale_date: "آخر بيع",
  last_movement_date: "آخر حركة",
  expiry_date: "تاريخ الصلاحية",
  total: "الإجمالي",
  subtotal: "قبل الخصم",
  gross_sales: "إجمالي المبيعات",
  net_sales: "صافي المبيعات",
  sales_total: "إجمالي المبيعات",
  total_sales: "إجمالي المبيعات",
  total_purchases: "إجمالي المشتريات",
  purchases_total: "إجمالي المشتريات",
  total_spent: "إجمالي الإنفاق",
  total_amount: "إجمالي المبلغ",
  total_billed: "إجمالي الفواتير",
  total_due: "إجمالي المستحق",
  total_cost: "إجمالي التكلفة",
  line_total: "إجمالي السطر",
  total_value: "إجمالي القيمة",
  total_value_wacc: "القيمة بمتوسط التكلفة",
  total_value_last_purchase: "القيمة بآخر شراء",
  total_discount: "إجمالي الخصم",
  discount_total: "إجمالي الخصم",
  discount: "الخصم",
  avg_discount: "متوسط الخصم",
  avg_discount_percent: "متوسط الخصم %",
  discount_range: "نطاق الخصم",
  return_total: "إجمالي المرتجع",
  returns_total: "إجمالي المرتجعات",
  returns_amount: "قيمة المرتجعات",
  return_amount: "قيمة المرتجع",
  vat_reversed: "الضريبة المستردة",
  revenue: "الإيراد",
  cost: "التكلفة",
  cost_price: "سعر التكلفة",
  unit_price: "سعر الوحدة",
  unit_cost: "تكلفة الوحدة",
  wacc: "متوسط التكلفة",
  last_purchase_cost: "آخر تكلفة شراء",
  avg_unit_cost: "متوسط تكلفة الوحدة",
  avg_unit_price: "متوسط سعر الوحدة",
  sale_price: "سعر البيع",
  purchase_price: "سعر الشراء",
  gross_profit: "مجمل الربح",
  profit_margin: "هامش الربح",
  margin_percent: "هامش الربح %",
  current_margin_percent: "الهامش الحالي %",
  min_margin_percent: "الحد الأدنى %",
  suggested_price: "السعر المقترح",
  below_threshold: "تحت الحد",
  quantity: "الكمية",
  quantity_sold: "الكمية المباعة",
  quantity_purchased: "الكمية المشتراة",
  stock_quantity: "رصيد المخزون",
  system_quantity: "رصيد النظام",
  total_quantity: "إجمالي الكمية",
  before_qty: "الرصيد قبل",
  after_qty: "الرصيد بعد",
  min_stock_qty: "حد أدنى للمخزون",
  unit_name: "الوحدة",
  item_count: "عدد الأصناف",
  invoice_count: "عدد الفواتير",
  purchase_count: "عدد المشتريات",
  return_count: "عدد المرتجعات",
  returns_count: "عدد المرتجعات",
  cancelled_count: "الفواتير الملغاة",
  returns_handled: "المرتجعات المعالجة",
  items_returned: "الأصناف المرتجعة",
  transaction_count: "عدد المعاملات",
  action_count: "عدد العمليات",
  total_invoices: "عدد الفواتير",
  total_items_sold: "عدد الأصناف المباعة",
  distinct_suppliers: "عدد الموردين",
  supplier_count: "عدد الموردين",
  customer_count: "عدد العملاء",
  category_name: "الفئة",
  payment_type: "طريقة الدفع",
  status: "الحالة",
  type: "النوع",
  source: "المصدر",
  movement_type: "نوع الحركة",
  reference_type: "نوع المرجع",
  reference_id: "رقم المرجع",
  resource: "المورد",
  action: "الإجراء",
  payload_json: "التفاصيل",
  user_id: "المستخدم",
  warehouse_id: "المخزن",
  balance: "الرصيد",
  opening_balance: "الرصيد الافتتاحي",
  closing_balance: "الرصيد الختامي",
  running_balance: "الرصيد الجاري",
  opening_cash: "النقدية الافتتاحية",
  closing_cash: "النقدية الختامية",
  expected_cash: "النقدية المتوقعة",
  cash_variance: "فرق النقدية",
  variance: "الفرق",
  collected: "المحصل",
  outstanding: "المستحق",
  collection_rate: "نسبة التحصيل %",
  days_to_collect: "أيام التحصيل",
  aging_0_30: "0-30 يوم",
  aging_31_60: "31-60 يوم",
  aging_61_90: "61-90 يوم",
  aging_90_plus: "أكثر من 90 يوم",
  days_until_expiry: "أيام حتى الصلاحية",
  days_since_last_movement: "أيام منذ آخر حركة",
  days_since_last_sale: "أيام منذ آخر بيع",
  aging_bucket: "فئة العمر",
  stock_status: "حالة المخزون",
  expiry_status: "حالة الصلاحية",
  tax_rate: "نسبة الضريبة",
  taxable_sales: "المبيعات الخاضعة",
  taxable_amount: "المبلغ الخاضع",
  vat_amount: "قيمة الضريبة",
  output_vat: "ضريبة المخرجات",
  input_vat: "ضريبة المدخلات",
  net_vat: "صافي الضريبة",
  amount: "المبلغ",
  pct: "النسبة %",
  section: "البند",
  label: "البيان",
  period: "الفترة",
  hour_slot: "الساعة",
  weekday: "يوم الأسبوع",
  weekday_name: "يوم الأسبوع",
  weekday_num: "رقم اليوم",
  avg_sale: "متوسط البيع",
  avg_transaction: "متوسط المعاملة",
  avg_invoice_value: "متوسط الفاتورة",
  avg_order_value: "متوسط الطلب",
  payment_method: "وسيلة الدفع",
  refund_method: "وسيلة الاسترداد",
  reason: "السبب",
  exception_type: "نوع الاستثناء",
  shift_id: "رقم الوردية",
  tx_count: "عدد الحركات",
  percentage: "النسبة %",
  running_total: "الإجمالي التراكمي",
  batch_no: "رقم الدفعة",
  potential_revenue: "إيراد محتمل",
  suggested_order_qty: "كمية الطلب المقترحة",
  estimated_order_cost: "تكلفة الطلب المقدرة",
  preferred_supplier: "المورد المفضل",
  loyalty_points: "نقاط الولاء",
  loyalty_tier: "شريحة الولاء",
  // ── Additional labels from actual SQL output ──
  gross_profit: "إجمالي الربح",
  total_gross_profit: "إجمالي الربح الإجمالي",
  gross_sales: "إجمالي المبيعات",
  net_sales: "صافي المبيعات",
  sales_total: "إجمالي المبيعات",
  avg_invoice_value: "متوسط قيمة الفاتورة",
  avg_transaction: "متوسط المعاملة",
  avg_order_value: "متوسط الطلب",
  avg_sale: "متوسط البيع",
  avg_discount: "متوسط الخصم",
  avg_unit_cost: "متوسط تكلفة الوحدة",
  avg_unit_price: "متوسط سعر الوحدة",
  running_balance: "الرصيد الجاري",
  opening_balance: "الرصيد الافتتاحي",
  closing_balance: "الرصيد الختامي",
  expected_cash: "النقدية المتوقعة",
  cash_variance: "فرق النقدية",
  opening_cash: "النقدية الافتتاحية",
  closing_cash: "النقدية الختامية",
  distinct_suppliers: "عدد الموردين المميزين",
  potential_revenue: "الإيراد المحتمل",
  suggested_order_qty: "كمية الطلب المقترحة",
  estimated_order_cost: "تكلفة الطلب المقدرة",
  preferred_supplier: "المورد المفضل",
  returns_handled: "المرتجعات المعالجة",
  items_returned: "الأصناف المرتجعة",
  payment_method: "وسيلة الدفع",
  refund_method: "وسيلة الاسترداد",
  exception_type: "نوع الاستثناء",
  tx_count: "عدد الحركات",
  percentage: "النسبة المئوية",
  running_total: "الإجمالي التراكمي",
  batch_no: "رقم الدفعة",
  opening_balance: "الرصيد الافتتاحي",
  net_vat: "صافي الضريبة",
  total_value: "القيمة الإجمالية",
  total_value_wacc: "القيمة (متوسط التكلفة)",
  total_value_last_purchase: "القيمة (آخر سعر شراء)",
  total_billed: "إجمالي الفواتير",
  total_due: "إجمالي المستحق",
  line_total: "إجمالي السطر",
  unit_price: "سعر الوحدة",
  unit_cost: "تكلفة الوحدة",
  sale_price: "سعر البيع",
  purchase_price: "سعر الشراء",
  current_margin_percent: "الهامش الحالي %",
  min_margin_percent: "الحد الأدنى للهامش %",
  suggested_price: "السعر المقترح",
  below_threshold: "تحت الحد الأدنى",
  stock_status: "حالة المخزون",
  expiry_status: "حالة الصلاحية",
  taxable_sales: "المبيعات الخاضعة للضريبة",
  taxable_amount: "المبلغ الخاضع للضريبة",
  vat_amount: "قيمة الضريبة",
  output_vat: "ضريبة المخرجات",
  input_vat: "ضريبة المدخلات",
  last_purchase_cost: "آخر تكلفة شراء",
  wacc: "متوسط التكلفة المرجح",
  profit_margin: "هامش الربح",
  margin_percent: "نسبة هامش الربح",
  item_name: "اسم الصنف",
  category_name: "اسم الفئة",
  customer_name: "اسم العميل",
  supplier_name: "اسم المورد",
  unit_name: "اسم الوحدة",
  weekday_name: "اسم اليوم",
  full_name: "الاسم الكامل",
  username: "اسم المستخدم",
  role: "الصلاحية",
  admin: "مدير",
  cashier: "كاشير",
  manager: "مشرف",
  status: "الحالة",
  last_login: "آخر تسجيل دخول",
  shift_count: "عدد الورديات",
  details: "التفاصيل",
  phone: "رقم الهاتف",
  invoice_no: "رقم الفاتورة",
  doc_no: "رقم المستند",
  purchase_no: "رقم المشتريات",
  ref_no: "رقم المرجع",
  return_ref: "رقم المرتجع",
  warehouse_id: "المخزن",
  cashier: "الكاشير",
  handled_by: "تم بواسطة",
  created_by: "أنشئ بواسطة",
  user_id: "المستخدم",
  action: "الإجراء",
  resource: "المورد",
  payload_json: "التفاصيل",
  movement_type: "نوع الحركة",
  reference_type: "نوع المرجع",
  reference_id: "رقم المرجع",
  before_qty: "الرصيد قبل",
  after_qty: "الرصيد بعد",
  min_stock_qty: "الحد الأدنى للكمية",
  stock_quantity: "كمية المخزون",
  system_quantity: "كمية النظام",
  total_quantity: "إجمالي الكمية",
  quantity_sold: "الكمية المباعة",
  quantity_purchased: "الكمية المشتراة",
  invoice_count: "عدد الفواتير",
  purchase_count: "عدد المشتريات",
  return_count: "عدد المرتجعات",
  returns_count: "عدد المرتجعات",
  cancelled_count: "عدد الملغاة",
  item_count: "عدد الأصناف",
  transaction_count: "عدد المعاملات",
  action_count: "عدد العمليات",
  total_invoices: "إجمالي الفواتير",
  total_items_sold: "إجمالي الأصناف المباعة",
  supplier_count: "عدد الموردين",
  customer_count: "عدد العملاء",
  days_until_expiry: "الأيام حتى الصلاحية",
  days_since_last_movement: "أيام منذ آخر حركة",
  days_since_last_sale: "أيام منذ آخر بيع",
  days_to_collect: "أيام التحصيل",
  aging_0_30: "0-30 يوم",
  aging_31_60: "31-60 يوم",
  aging_61_90: "61-90 يوم",
  aging_90_plus: "أكثر من 90 يوم",
  aging_bucket: "فئة العمر",
  collected: "المحصل",
  outstanding: "المستحق",
  collection_rate: "نسبة التحصيل",
  last_sale_date: "آخر تاريخ بيع",
  last_purchase_date: "آخر تاريخ شراء",
  last_invoice_date: "آخر تاريخ فاتورة",
  last_movement_date: "آخر تاريخ حركة",
  expiry_date: "تاريخ الصلاحية",
};

const REPORT_COLUMN_KEYS = {
  "daily-sales": ["date", "invoice_count", "gross_sales", "total_discount", "net_sales", "returns_amount", "returns_count", "total_cost", "gross_profit"],
  "detailed-sales": ["invoice_no", "date", "customer_name", "cashier", "payment_type", "status", "subtotal", "discount", "total", "item_count"],
  "sales-by-item": ["item_code", "item_name", "category_name", "quantity_sold", "revenue", "discount_total", "cost", "profit_margin", "margin_percent", "avg_unit_price"],
  "sales-by-category": ["category_name", "item_count", "quantity_sold", "revenue", "discount_total", "cost", "profit_margin", "margin_percent"],
  "sales-by-cashier": ["cashier", "invoice_count", "cancelled_count", "total_sales", "total_discount", "avg_invoice_value", "total_items_sold", "returns_handled"],
  "sales-by-payment": ["payment_type", "invoice_count", "total_sales", "total_discount", "avg_transaction", "returns_amount"],
  "sales-heatmap": ["weekday_name", "hour_slot", "invoice_count", "total_sales", "avg_sale"],
  "exceptions": ["invoice_no", "date", "customer_name", "exception_type", "discount", "status", "total"],
  "period-comparison": ["period", "date", "invoice_count", "total_sales", "total_discount"],
  "gross-net-sales": ["date", "gross_sales", "total_discount", "net_sales", "invoice_count", "returns_amount", "total_cost", "gross_profit"],
  "sales-returns": ["return_ref", "invoice_no", "date", "customer_name", "handled_by", "return_total", "reason", "refund_method", "items_returned"],
  "discount-analysis": ["section", "payment_type", "discount_range", "invoice_count", "total_discount", "avg_discount", "avg_discount_percent", "total_sales"],
  "margin-by-item": ["item_code", "item_name", "quantity_sold", "revenue", "cost", "profit_margin", "margin_percent"],
  "margin-by-category": ["category_name", "quantity_sold", "revenue", "cost", "profit_margin", "margin_percent"],
  "margin-health": ["item_code", "item_name", "wacc", "sale_price", "current_margin_percent", "min_margin_percent", "suggested_price", "below_threshold"],
  "shift-history": ["id", "cashier", "opened_date", "closed_at", "opening_cash", "closing_cash", "sales_total", "expected_cash", "cash_variance", "invoice_count", "status"],
  "purchase-summary": ["date", "purchase_count", "distinct_suppliers", "total_purchases", "avg_order_value"],
  "detailed-purchases": ["id", "purchase_no", "date", "supplier_name", "total", "status", "payment_type", "created_by", "item_count"],
  "purchases-by-supplier": ["supplier_name", "purchase_count", "total_purchases", "avg_order_value", "returns_total", "last_purchase_date"],
  "purchases-by-item": ["item_code", "item_name", "quantity_purchased", "total_cost", "avg_unit_cost", "distinct_suppliers", "last_purchase_date"],
  "purchase-returns": ["return_ref", "supplier_name", "date", "return_total", "reason", "refund_method", "items_returned"],
  "supplier-pricing": ["supplier_name", "item_name", "unit_price", "quantity", "line_total", "purchase_date"],
  "slow-moving": ["item_code", "item_name", "category_name", "stock_quantity", "cost_price", "total_value", "potential_revenue", "last_sale_date"],
  "stock-levels": ["item_code", "item_name", "category_name", "warehouse_id", "quantity", "min_stock_qty", "unit_name", "total_value", "stock_status"],
  "stock-movements": ["item_code", "item_name", "movement_type", "reference_type", "reference_id", "warehouse_id", "before_qty", "after_qty", "quantity", "created_by", "date"],
  "stock-valuation": ["item_code", "name", "category_name", "warehouse_id", "total_quantity", "wacc", "last_purchase_cost", "total_value"],
  "count-sheet": ["item_code", "item_name", "barcode", "category_name", "warehouse_id", "system_quantity", "unit_name"],
  "reorder": ["item_code", "item_name", "stock_quantity", "min_stock_qty", "suggested_order_qty", "estimated_order_cost", "preferred_supplier"],
  "expiry": ["batch_no", "item_code", "item_name", "quantity", "expiry_date", "cost_price", "days_until_expiry", "expiry_status"],
  "inventory-aging": ["item_code", "item_name", "quantity", "wacc", "total_value", "last_movement_date", "days_since_last_movement", "aging_bucket"],
  "dead-stock": ["item_code", "item_name", "category_name", "quantity", "wacc", "total_value", "last_sale_date", "days_since_last_sale", "aging_bucket"],
  "ar-aging": ["customer_name", "phone", "invoice_count", "total_due", "aging_0_30", "aging_31_60", "aging_61_90", "aging_90_plus", "last_invoice_date"],
  "ap-aging": ["supplier_name", "phone", "purchase_count", "total_due", "aging_0_30", "aging_31_60", "aging_61_90", "aging_90_plus", "last_purchase_date"],
  "profit-loss": ["label", "amount", "pct", "section"],
  "customer-statement": ["ref_no", "date", "type", "amount", "status", "running_balance"],
  "top-customers": ["customer_name", "phone", "invoice_count", "total_spent", "avg_order_value", "last_purchase_date", "loyalty_points", "loyalty_tier"],
  "collection-efficiency": ["customer_name", "total_invoices", "total_billed", "collected", "outstanding", "collection_rate", "days_to_collect"],
  "supplier-statement": ["ref_no", "date", "type", "amount", "status", "running_balance"],
  "cash-flow": ["date", "type", "total"],
  "treasury": ["name", "code", "balance", "source", "tx_count"],
  "cash-consistency": ["date", "shift_id", "cashier", "opening_cash", "closing_cash", "sales_total", "expected_cash", "cash_variance", "invoice_count", "status"],
  "payment-method-flow": ["payment_type", "date", "transaction_count", "total_amount", "running_total"],
  "bank-cash-split": ["type", "name", "balance", "percentage"],
  "reconciliation-exceptions": ["date", "shift_id", "cashier", "opening_cash", "closing_cash", "sales_total", "expected_cash", "cash_variance", "invoice_count", "status"],
  "vat": ["tax_rate", "taxable_sales", "vat_amount", "invoice_count"],
  "output-vat": ["tax_rate", "taxable_amount", "vat_amount", "invoice_count", "customer_count"],
  "input-vat": ["tax_rate", "taxable_amount", "vat_amount", "purchase_count", "supplier_count"],
  "vat-filing-summary": ["sales_total", "output_vat", "purchases_total", "input_vat"],
  "returns-tax-effect": ["return_ref", "date", "return_amount", "vat_reversed", "items_returned"],
  "audit-log": ["id", "user_id", "full_name", "action", "resource", "payload_json", "created_at"],
  "user-activity": ["user_id", "full_name", "action", "resource", "action_count", "date"],
  "sales-returns-summary": ["date", "return_count", "returns_total", "customer_count", "items_returned"],
  "sales-returns-by-customer": ["customer_name", "return_count", "returns_total", "last_return_date"],
  "purchase-returns-summary": ["date", "return_count", "returns_total", "supplier_count", "items_returned"],
  "purchase-returns-by-supplier": ["supplier_name", "return_count", "returns_total", "last_return_date"],
  "customer-loyalty": ["customer_name", "phone", "loyalty_points", "loyalty_tier", "total_spent", "invoice_count", "last_purchase_date"],
  "supplier-purchases-history": ["purchase_no", "date", "supplier_name", "total", "status", "payment_type", "item_count", "created_by"],
  "supplier-returns-history": ["return_ref", "date", "supplier_name", "return_total", "reason", "refund_method", "items_returned"],
  "daily-sessions": ["date", "cashier", "opening_cash", "closing_cash", "sales_total", "total_discount", "invoice_count", "cash_variance", "status"],
  "withdrawals-report": ["id", "reference_no", "date", "amount", "reason", "status", "treasury_name", "created_by"],
  "expense-summary": ["date", "expense_count", "total_expenses", "category_count"],
  "detailed-expenses": ["id", "date", "category_name", "amount", "payment_type", "description", "created_by"],
  "expenses-by-category": ["category_name", "expense_count", "total_amount", "percentage"],
  "expenses-by-payment": ["payment_type", "expense_count", "total_amount"],
  "revenue-summary": ["date", "revenue_count", "total_revenue", "category_count"],
  "detailed-revenues": ["id", "date", "category_name", "amount", "payment_type", "description", "created_by"],
  "revenues-by-category": ["category_name", "revenue_count", "total_amount", "percentage"],
  "revenues-by-payment": ["payment_type", "revenue_count", "total_amount"],
  "cheque-listing": ["cheque_no", "date", "bank_name", "amount", "status", "due_date", "payee_name"],
  "bank-transactions": ["date", "bank_name", "type", "amount", "reference_no", "description"],
  "bank-summary": ["bank_name", "account_no", "balance", "available_balance", "tx_count"],
  "installment-plans": ["customer_name", "total_amount", "paid_amount", "outstanding", "installment_count", "start_date", "status"],
  "installment-collections": ["date", "customer_name", "installment_no", "amount", "payment_type", "status"],
  "installments-by-customer": ["customer_name", "total_plans", "total_amount", "collected", "outstanding", "overdue"],
  "installment-delinquent": ["customer_name", "plan_id", "overdue_amount", "due_date", "days_overdue"],
  "branch-transfers": ["transfer_no", "date", "from_warehouse", "to_warehouse", "item_name", "quantity", "status", "created_by"],
  "warehouse-levels": ["item_code", "item_name", "warehouse", "quantity", "min_stock_qty", "stock_status", "total_value"],
  "warehouse-levels-summary": ["warehouse", "item_count", "total_quantity", "total_value"],
  "employee-adjustments": ["date", "employee_name", "adjustment_type", "amount", "reason", "status"],
  "user-list": ["id", "username", "full_name", "role", "status", "created_at", "last_login"],
  "user-performance": ["full_name", "invoice_count", "total_sales", "total_discount", "avg_invoice_value", "returns_handled", "returns_amount", "shift_count"],
  "login-history": ["id", "full_name", "action", "date", "details", "resource"],
  "profit-by-category": ["category_name", "revenue", "cost", "profit_margin", "margin_percent", "quantity_sold"],
  "profit-by-customer": ["customer_name", "revenue", "cost", "profit_margin", "margin_percent", "invoice_count"],
  "profit-by-period": ["period", "revenue", "cost", "profit_margin", "margin_percent", "invoice_count"],
};

const CODE_KEYS = new Set(["id", "item_code", "code", "sku", "barcode", "invoice_no", "purchase_no", "ref_no", "return_ref", "reference_id", "shift_id", "user_id", "warehouse_id", "batch_no", "section"]);
const DATE_KEYS = new Set(["date", "created_at", "opened_date", "closed_at", "purchase_date", "last_purchase_date", "last_invoice_date", "last_sale_date", "last_movement_date", "expiry_date", "updated_at"]);
const PERCENT_KEYS = new Set(["pct", "margin_percent", "current_margin_percent", "min_margin_percent", "avg_discount_percent", "collection_rate", "percentage", "tax_rate", "avg_discount_percent", "collection_rate"]);
const NUMBER_KEYS = new Set(["quantity", "quantity_sold", "quantity_purchased", "stock_quantity", "system_quantity", "total_quantity", "before_qty", "after_qty", "min_stock_qty", "item_count", "invoice_count", "purchase_count", "returns_count", "return_count", "items_returned", "transaction_count", "action_count", "total_invoices", "total_items_sold", "distinct_suppliers", "supplier_count", "customer_count", "tx_count", "days_until_expiry", "days_since_last_movement", "days_since_last_sale", "days_to_collect", "weekday_num", "cancelled_count", "loyalty_points", "suggested_order_qty", "returns_handled", "weekday_num", "shift_count"]);

function inferType(key) {
  if (CODE_KEYS.has(key)) return "code";
  if (DATE_KEYS.has(key) || key.endsWith("_date")) return "date";
  if (PERCENT_KEYS.has(key) || key.endsWith("_percent")) return "percent";
  if (NUMBER_KEYS.has(key) || key.endsWith("_count")) return "number";
  if (key.includes("price") || key.includes("cost") || key.includes("total") || key.includes("amount") || key.includes("balance") || key.includes("sales") || key.includes("profit") || key.includes("discount") || key.includes("vat") || key.includes("cash") || key.includes("revenue") || key.includes("value") || key.includes("collected") || key.includes("outstanding") || key.includes("due")) return "money";
  return "text";
}

function inferPriority(key, index) {
  if (index < 5) return "essential";
  if (index < 9) return "useful";
  return "optional";
}

function labelForKey(key) {
  return AR_LABELS[key] || key;
}

function buildColumn(key, index = 0) {
  return {
    key,
    label: labelForKey(key),
    type: inferType(key),
    printPriority: inferPriority(key, index),
    defaultVisible: index < 10,
  };
}

function orderKeys(keys, slug) {
  const preferred = REPORT_COLUMN_KEYS[slug] || [];
  const used = new Set();
  const ordered = [];
  preferred.forEach((key) => {
    if (keys.includes(key) && !used.has(key)) {
      ordered.push(key);
      used.add(key);
    }
  });
  keys.forEach((key) => {
    if (!used.has(key)) ordered.push(key);
  });
  return ordered;
}

function getReportColumns(slug, rows = []) {
  const rowKeys = Object.keys(rows?.[0] || {});
  const catalogKeys = REPORT_COLUMN_KEYS[slug] || [];
  const keys = rowKeys.length ? orderKeys(rowKeys, slug) : catalogKeys;
  return keys.map(buildColumn);
}

function getReportTitle(slug, fallback = "") {
  return REPORT_TITLES[slug] || fallback || slug;
}

function normalizeStructuredReport(data) {
  if (!data || typeof data !== "object" || Array.isArray(data)) return null;
  if (Array.isArray(data.transactions)) {
    const summary = { ...data };
    delete summary.transactions;
    return { rows: data.transactions, sections: [], summary };
  }
  const sections = [];
  ["by_payment", "by_range"].forEach((key) => {
    if (Array.isArray(data[key])) {
      const sectionLabel = key === "by_payment" ? "حسب طريقة الدفع" : "حسب نطاق الخصم";
      sections.push({ key, label: sectionLabel, rows: data[key] });
    }
  });
  if (sections.length) {
    const rows = sections.flatMap((section) => section.rows.map((row) => ({ section: section.label, ...row })));
    return { rows, sections, summary: null };
  }
  return null;
}

module.exports = {
  REPORT_COLUMN_KEYS,
  REPORT_TITLES,
  labelForKey,
  getReportColumns,
  getReportTitle,
  normalizeStructuredReport,
};
