/**
 * helpContent.js — Complete Smart Help Tour Definitions
 * Spec Part B: Every page, every section, every field
 * ~120 step definitions across all pages
 */

export const helpContent = {

  /* ── LOGIN ──────────────────────────────────────── */
  login: {
    title_ar: 'مرحباً بك — تسجيل الدخول',
    title_en: 'Welcome — Login',
    steps: [
      {
        id: 'login_username',
        target: '[data-help="login-username"]',
        title_ar: 'اسم المستخدم',
        title_en: 'Username',
        body_ar: 'أدخل اسم المستخدم الخاص بك. الإعداد الافتراضي للمدير هو "admin".',
        body_en: 'Enter your username. The default admin username is "admin".',
        placement: 'bottom',
        highlight_type: 'spotlight',
      },
      {
        id: 'login_password',
        target: '[data-help="login-password"]',
        title_ar: 'كلمة المرور',
        title_en: 'Password',
        body_ar: 'أدخل كلمة المرور. اضغط على أيقونة العين لإظهار أو إخفاء النص.',
        body_en: 'Enter your password. Click the eye icon to show/hide.',
        placement: 'bottom',
        highlight_type: 'spotlight',
      },
      {
        id: 'login_btn',
        target: '[data-help="login-btn"]',
        title_ar: 'تسجيل الدخول',
        title_en: 'Sign In',
        body_ar: 'اضغط هنا للدخول، أو اضغط Enter من لوحة المفاتيح.',
        body_en: 'Click to sign in, or press Enter on your keyboard.',
        placement: 'top',
        highlight_type: 'glow',
      },
    ],
    tooltips: {},
  },

  /* ── SETUP WIZARD ───────────────────────────────── */
  setup_wizard: {
    title_ar: 'معالج الإعداد الأولي',
    title_en: 'Setup Wizard',
    steps: [
      {
        id: 'wizard_progress',
        target: '[data-help="wizard-progress"]',
        title_ar: 'مراحل الإعداد',
        title_en: 'Setup Steps',
        body_ar: 'خمس خطوات فقط لإعداد النظام كاملاً. يمكنك الرجوع في أي وقت.',
        body_en: 'Just five steps to complete setup. You can go back anytime.',
        placement: 'bottom',
        highlight_type: 'spotlight',
      },
      {
        id: 'wizard_company',
        target: '[data-help="wizard-company-name"]',
        title_ar: 'اسم الشركة',
        title_en: 'Company Name',
        body_ar: 'سيظهر هذا الاسم على جميع الفواتير والإيصالات والتقارير.',
        body_en: 'This name appears on all invoices, receipts, and reports.',
        placement: 'bottom',
      },
      {
        id: 'wizard_branch',
        target: '[data-help="wizard-branch-code"]',
        title_ar: 'رمز الفرع',
        title_en: 'Branch Code',
        body_ar: 'رمز قصير (2-4 أحرف) يُستخدم في تسلسل أرقام الفواتير. مثال: BR1',
        body_en: 'Short code (2-4 chars) used in invoice numbering. Example: BR1',
        placement: 'bottom',
      },
      {
        id: 'wizard_currency',
        target: '[data-help="wizard-currency"]',
        title_ar: 'العملة',
        title_en: 'Currency',
        body_ar: 'اختر عملة النظام. تظهر هذه العملة على كل الفواتير والتقارير المالية.',
        body_en: 'Choose your system currency. Shown on all invoices and financial reports.',
        placement: 'bottom',
      },
      {
        id: 'wizard_logo',
        target: '[data-help="wizard-logo"]',
        title_ar: 'شعار الشركة',
        title_en: 'Company Logo',
        body_ar: 'ارفع صورة الشعار لتظهر على الفواتير. يُفضل PNG بخلفية شفافة.',
        body_en: 'Upload your logo to appear on invoices. Prefer PNG with transparent background.',
        placement: 'bottom',
      },
    ],
    tooltips: {},
  },

  /* ── DASHBOARD ──────────────────────────────────── */
  dashboard: {
    title_ar: 'لوحة التحكم',
    title_en: 'Dashboard',
    steps: [
      {
        id: 'dash_kpi_sales',
        target: '[data-help="dash-kpi-sales"]',
        title_ar: 'مبيعات اليوم',
        title_en: "Today's Sales",
        body_ar: 'إجمالي قيمة الفواتير المحفوظة اليوم. يُحدَّث فور حفظ أي فاتورة.',
        body_en: 'Total value of invoices saved today. Updates instantly on every save.',
        placement: 'bottom',
        highlight_type: 'glow',
      },
      {
        id: 'dash_kpi_invoices',
        target: '[data-help="dash-kpi-invoices"]',
        title_ar: 'عدد الفواتير',
        title_en: 'Invoice Count',
        body_ar: 'عدد فواتير البيع المكتملة اليوم فقط.',
        body_en: 'Number of completed sales invoices today.',
        placement: 'bottom',
      },
      {
        id: 'dash_kpi_profit',
        target: '[data-help="dash-kpi-profit"]',
        title_ar: 'الأرباح الصافية',
        title_en: 'Net Profit',
        body_ar: 'الأرباح = صافي المبيعات − تكلفة البضاعة − المصروفات. يحتاج إدخال مشتريات لحساب دقيق.',
        body_en: 'Profit = Net sales − COGS − Expenses. Requires purchase data for accuracy.',
        placement: 'bottom',
      },
      {
        id: 'dash_revenue_chart',
        target: '[data-help="dash-revenue-chart"]',
        title_ar: 'مخطط الإيرادات',
        title_en: 'Revenue Chart',
        body_ar: 'يُظهر مبيعات الأيام أو الأشهر الماضية. انقر على الخطوط لتصفية نوع البيانات.',
        body_en: 'Shows past days or months sales. Click lines to filter data type.',
        placement: 'top',
      },
      {
        id: 'dash_quick_actions',
        target: '[data-help="dash-quick-actions"]',
        title_ar: 'الإجراءات السريعة',
        title_en: 'Quick Actions',
        body_ar: 'اختصارات للعمليات الأكثر استخداماً. يمكن تخصيصها من الإعدادات.',
        body_en: 'Shortcuts to most-used operations. Customizable from Settings.',
        placement: 'top',
      },
      {
        id: 'dash_low_stock',
        target: '[data-help="dash-low-stock"]',
        title_ar: 'تنبيهات المخزون',
        title_en: 'Stock Alerts',
        body_ar: 'الأصناف التي وصلت لأقل من الحد الأدنى المحدد. اضغط للذهاب لصفحة المخزون.',
        body_en: 'Items below minimum threshold. Tap to go to the inventory page.',
        placement: 'start',
      },
    ],
    tooltips: {},
  },

  /* ── POS SCREEN ─────────────────────────────────── */
  pos_sales: {
    title_ar: 'مرحباً بك في شاشة نقطة البيع',
    title_en: 'Welcome to the POS Screen',
    steps: [
      {
        id: 'pos_shift_bar',
        target: '[data-help="pos-shift-bar"]',
        title_ar: 'شريط الوردية',
        title_en: 'Shift Bar',
        body_ar: 'يجب فتح وردية قبل البيع. يظهر هنا رقم الوردية والوقت المنقضي.',
        body_en: 'A shift must be open before selling. Shows shift number and elapsed time.',
        placement: 'bottom',
        highlight_type: 'glow',
      },
      {
        id: 'pos_search',
        target: '[data-help="pos-search"]',
        title_ar: 'البحث ومسح الباركود',
        title_en: 'Search & Barcode Scan',
        body_ar: 'اكتب اسم الصنف أو رقمه، أو امسح الباركود مباشرةً. مفتاح الاختصار: F2',
        body_en: 'Type item name or code, or scan the barcode. Shortcut: F2',
        placement: 'bottom',
      },
      {
        id: 'pos_category_tabs',
        target: '[data-help="pos-category-tabs"]',
        title_ar: 'تصفية حسب الفئة',
        title_en: 'Category Filter',
        body_ar: 'اضغط على فئة للتصفية. "الكل" لإلغاء التصفية.',
        body_en: 'Tap a category to filter. "All" to clear the filter.',
        placement: 'bottom',
      },
      {
        id: 'pos_item_grid',
        target: '[data-help="pos-item-grid"]',
        title_ar: 'شبكة الأصناف',
        title_en: 'Item Grid',
        body_ar: 'اضغط على أي صنف لإضافته للفاتورة مباشرةً. الأصناف المنفدة باللون الرمادي.',
        body_en: 'Tap any item to add to invoice. Out-of-stock items appear grayed out.',
        placement: 'start',
      },
      {
        id: 'pos_customer',
        target: '[data-help="pos-customer"]',
        title_ar: 'اختيار العميل',
        title_en: 'Select Customer',
        body_ar: 'ابحث بالاسم أو الهاتف. مطلوب للبيع الآجل. اضغط F1 كاختصار.',
        body_en: 'Search by name or phone. Required for credit sales. Shortcut: F1',
        placement: 'start',
      },
      {
        id: 'pos_invoice_lines',
        target: '[data-help="pos-invoice-lines"]',
        title_ar: 'بنود الفاتورة',
        title_en: 'Invoice Lines',
        body_ar: 'كل صنف مضاف يظهر هنا. اضغط على الكمية لتعديلها مباشرةً.',
        body_en: 'Added items appear here. Tap quantity to edit it inline.',
        placement: 'end',
      },
      {
        id: 'pos_discount',
        target: '[data-help="pos-discount"]',
        title_ar: 'الخصم',
        title_en: 'Discount',
        body_ar: 'أدخل الخصم كمبلغ ثابت أو نسبة مئوية. اضغط على الزر للتبديل بينهما.',
        body_en: 'Enter discount as fixed amount or percentage. Toggle with the button.',
        placement: 'top',
      },
      {
        id: 'pos_payment',
        target: '[data-help="pos-payment"]',
        title_ar: 'طريقة الدفع',
        title_en: 'Payment Method',
        body_ar: 'اختر نقداً، آجل، بطاقة، أو متعدد. الدفع المتعدد يتيح تقسيم المبلغ.',
        body_en: 'Choose cash, credit, card, or split. Split allows dividing the amount.',
        placement: 'top',
      },
      {
        id: 'pos_total',
        target: '[data-help="pos-total"]',
        title_ar: 'الإجمالي',
        title_en: 'Total',
        body_ar: 'المبلغ النهائي بعد الخصومات والضرائب. يتحدث فور كل تغيير.',
        body_en: 'Final amount after discounts and taxes. Updates on every change.',
        placement: 'top',
        highlight_type: 'glow',
      },
      {
        id: 'pos_save_btn',
        target: '[data-help="pos-save-btn"]',
        title_ar: 'حفظ الفاتورة',
        title_en: 'Save Invoice',
        body_ar: 'احفظ واطبع بضغطة واحدة. اختصار: F12. الزر الثاني للحفظ بدون طباعة.',
        body_en: 'Save and print in one tap. Shortcut: F12. Second button saves without printing.',
        placement: 'top',
        highlight_type: 'glow',
      },
      {
        id: 'pos_hold',
        target: '[data-help="pos-hold"]',
        title_ar: 'تعليق الفاتورة',
        title_en: 'Hold Invoice',
        body_ar: 'علّق الفاتورة لخدمة عميل آخر، ثم ارجع إليها من زر الاسترجاع.',
        body_en: 'Hold this invoice to serve another customer, then restore it later.',
        placement: 'top',
      },
    ],
    tooltips: {
      discount_field: {
        ar: 'أدخل قيمة الخصم كنسبة مئوية أو مبلغ ثابت. الخصم لا يمكن أن يتجاوز إجمالي السطر.',
        en: 'Enter discount as percentage or fixed amount. Cannot exceed the line total.',
      },
      hold_btn: {
        ar: 'تعليق الفاتورة يحفظها مؤقتاً حتى تتمكن من خدمة عميل آخر والعودة إليها لاحقاً.',
        en: 'Hold invoice saves it temporarily so you can serve another customer and return.',
      },
      customer_selector: {
        ar: 'اختر العميل لربط الفاتورة بحسابه. مطلوب للمبيعات الآجلة.',
        en: 'Select customer to link the invoice. Required for credit sales.',
      },
    },
  },

  /* ── ITEMS LIST ─────────────────────────────────── */
  items_list: {
    title_ar: 'صفحة الأصناف والأسعار',
    title_en: 'Items & Prices',
    steps: [
      {
        id: 'items_add_btn',
        target: '[data-help="items-add-btn"]',
        title_ar: 'إضافة صنف جديد',
        title_en: 'Add New Item',
        body_ar: 'اضغط لفتح نموذج إضافة صنف. يمكن الاستيراد من Excel للإضافة الجماعية.',
        body_en: 'Open the add item form. Use Excel import for bulk additions.',
        placement: 'bottom',
        highlight_type: 'glow',
      },
      {
        id: 'items_search',
        target: '[data-help="items-search"]',
        title_ar: 'البحث',
        title_en: 'Search',
        body_ar: 'ابحث بالاسم أو الباركود أو رمز الصنف. البحث فوري بدون ضغط Enter.',
        body_en: 'Search by name, barcode, or item code. Results appear instantly.',
        placement: 'bottom',
      },
      {
        id: 'items_filter',
        target: '[data-help="items-filter"]',
        title_ar: 'الفلاتر',
        title_en: 'Filters',
        body_ar: 'فلتر حسب الفئة، الحالة، نوع الصنف. يمكن تطبيق عدة فلاتر معاً.',
        body_en: 'Filter by category, status, item type. Multiple filters can stack.',
        placement: 'bottom',
      },
      {
        id: 'items_stock_col',
        target: '[data-help="items-stock-col"]',
        title_ar: 'عمود المخزون',
        title_en: 'Stock Column',
        body_ar: 'يُظهر الكمية الإجمالية في جميع المستودعات. اللون يشير لحالة المخزون.',
        body_en: 'Shows total quantity across all warehouses. Color indicates stock status.',
        placement: 'start',
      },
      {
        id: 'items_actions',
        target: '[data-help="items-actions"]',
        title_ar: 'أزرار الإجراءات',
        title_en: 'Action Buttons',
        body_ar: 'تظهر عند تمرير الماوس: تعديل، عرض تفاصيل، طباعة ملصق، حذف.',
        body_en: 'Appear on hover: edit, view details, print label, delete.',
        placement: 'start',
      },
      {
        id: 'items_import_btn',
        target: '[data-help="items-import-btn"]',
        title_ar: 'استيراد من Excel',
        title_en: 'Import from Excel',
        body_ar: 'حمّل نموذج Excel، أدخل بياناتك، ثم ارفعه لإضافة مئات الأصناف دفعة واحدة.',
        body_en: 'Download template, fill data, re-upload to add hundreds of items at once.',
        placement: 'bottom',
      },
    ],
    tooltips: {
      barcode_field: {
        ar: 'أدخل الباركود يدوياً أو اضغط زر المسح. تركه فارغاً سيُنشئ باركود تلقائياً.',
        en: 'Enter barcode manually or press scan. Leave empty to auto-generate.',
      },
    },
  },

  /* ── ITEM FORM ──────────────────────────────────── */
  item_form: {
    title_ar: 'نموذج الصنف',
    title_en: 'Item Form',
    steps: [
      {
        id: 'item_code',
        target: '[data-help="item-code"]',
        title_ar: 'رمز الصنف',
        title_en: 'Item Code',
        body_ar: 'رمز فريد لكل صنف. يُنشأ تلقائياً أو أدخله يدوياً. لا يمكن تكراره.',
        body_en: 'Unique code per item. Auto-generated or enter manually. Must be unique.',
        placement: 'bottom',
      },
      {
        id: 'item_barcode',
        target: '[data-help="item-barcode"]',
        title_ar: 'الباركود',
        title_en: 'Barcode',
        body_ar: 'أدخله يدوياً أو امسحه بالماسح. يمكن إضافة أكثر من باركود للصنف الواحد.',
        body_en: 'Enter manually or scan. You can add multiple barcodes per item.',
        placement: 'bottom',
      },
      {
        id: 'item_prices',
        target: '[data-help="item-prices"]',
        title_ar: 'أعمدة الأسعار',
        title_en: 'Price Columns',
        body_ar: 'السعر1 هو سعر التجزئة الرئيسي. السعر2 للجملة. السعر3 خاص. يُطبَّق حسب مجموعة العميل.',
        body_en: 'Price1 = retail. Price2 = wholesale. Price3 = special. Applied per customer group.',
        placement: 'top',
      },
      {
        id: 'item_min_stock',
        target: '[data-help="item-min-stock"]',
        title_ar: 'الحد الأدنى للمخزون',
        title_en: 'Minimum Stock',
        body_ar: 'عند الوصول لهذه الكمية يظهر تنبيه نفاد المخزون تلقائياً في لوحة التحكم.',
        body_en: 'When stock reaches this level a low-stock alert appears on the dashboard.',
        placement: 'bottom',
      },
      {
        id: 'item_track_serial',
        target: '[data-help="item-track-serial"]',
        title_ar: 'تتبع الأرقام التسلسلية',
        title_en: 'Serial Tracking',
        body_ar: 'فعّل هذا للأصناف التي لها أرقام تسلسلية مثل الأجهزة الإلكترونية.',
        body_en: 'Enable for items with serial numbers like electronics.',
        placement: 'bottom',
      },
      {
        id: 'item_image',
        target: '[data-help="item-image"]',
        title_ar: 'صورة الصنف',
        title_en: 'Item Image',
        body_ar: 'تُعرض في شبكة نقطة البيع. يُفضل صورة مربعة على خلفية بيضاء.',
        body_en: 'Shown in the POS grid. Prefer a square image with white background.',
        placement: 'start',
      },
    ],
    tooltips: {},
  },

  /* ── CUSTOMERS ──────────────────────────────────── */
  customers_list: {
    title_ar: 'صفحة العملاء',
    title_en: 'Customers',
    steps: [
      {
        id: 'cust_balance_col',
        target: '[data-help="cust-balance-col"]',
        title_ar: 'عمود الرصيد',
        title_en: 'Balance Column',
        body_ar: 'الرصيد الموجب = مبلغ مستحق على العميل. الصفر = لا توجد مديونية.',
        body_en: 'Positive balance = amount owed by customer. Zero = no outstanding debt.',
        placement: 'start',
      },
      {
        id: 'cust_credit_limit',
        target: '[data-help="cust-credit-limit"]',
        title_ar: 'حد الائتمان',
        title_en: 'Credit Limit',
        body_ar: 'أقصى مبلغ يمكن للعميل الشراء به آجلاً. الصفر يعني بدون حد.',
        body_en: 'Maximum credit purchase allowed. Zero = no limit.',
        placement: 'start',
      },
      {
        id: 'cust_statement_btn',
        target: '[data-help="cust-statement-btn"]',
        title_ar: 'كشف الحساب',
        title_en: 'Account Statement',
        body_ar: 'طباعة كشف حساب تفصيلي بكل المعاملات لفترة محددة.',
        body_en: 'Print a detailed account statement for a chosen period.',
        placement: 'start',
      },
      {
        id: 'cust_filter_balance',
        target: '[data-help="cust-filter-balance"]',
        title_ar: 'فلتر حسب الرصيد',
        title_en: 'Filter by Balance',
        body_ar: 'اعرض فقط العملاء الذين لديهم رصيد مستحق لتسريع عمليات التحصيل.',
        body_en: 'Show only customers with outstanding balance to speed up collections.',
        placement: 'bottom',
      },
    ],
    tooltips: {},
  },

  /* ── REPORTS CENTER ─────────────────────────────── */
  reports_center: {
    title_ar: 'مركز التقارير',
    title_en: 'Reports Center',
    steps: [
      {
        id: 'reports_search',
        target: '[data-help="reports-search"]',
        title_ar: 'البحث عن تقرير',
        title_en: 'Search Reports',
        body_ar: 'ابحث عن أي تقرير بالاسم. النتائج تُصفَّى فوراً أثناء الكتابة.',
        body_en: 'Search any report by name. Results filter instantly as you type.',
        placement: 'bottom',
      },
      {
        id: 'reports_categories',
        target: '[data-help="reports-categories"]',
        title_ar: 'فئات التقارير',
        title_en: 'Report Categories',
        body_ar: 'التقارير مجمّعة في فئات: مبيعات، مخزون، مالية، عملاء، كاشير. انقر للتصفية.',
        body_en: 'Reports grouped by: sales, inventory, finance, customers, cashier. Click to filter.',
        placement: 'bottom',
      },
      {
        id: 'reports_favorite',
        target: '[data-help="reports-favorite"]',
        title_ar: 'تثبيت التقارير المفضلة',
        title_en: 'Favorite Reports',
        body_ar: 'اضغط على نجمة أي تقرير لتثبيته في أعلى القائمة للوصول السريع.',
        body_en: 'Click the star icon on any report to pin it to the top for quick access.',
        placement: 'start',
      },
      {
        id: 'reports_quick_run',
        target: '[data-help="reports-quick-run"]',
        title_ar: 'تشغيل سريع',
        title_en: 'Quick Run',
        body_ar: 'يفتح التقرير بالفلاتر الأخيرة المستخدمة مباشرةً بدون إعادة الضبط.',
        body_en: 'Opens the report with last-used filters directly without reconfiguring.',
        placement: 'start',
      },
    ],
    tooltips: {},
  },

  /* ── SETTINGS ───────────────────────────────────── */
  settings_system: {
    title_ar: 'إعدادات النظام',
    title_en: 'System Settings',
    steps: [
      {
        id: 'settings_tabs',
        target: '[data-help="settings-tabs"]',
        title_ar: 'أقسام الإعدادات',
        title_en: 'Settings Sections',
        body_ar: 'تنقّل بين إعدادات الشركة، المالية، الطباعة، المستخدمين، والنظام من هنا.',
        body_en: 'Navigate between company, financial, printing, users, and system settings.',
        placement: 'bottom',
      },
      {
        id: 'settings_app_identity',
        target: '[data-help="settings-app-identity"]',
        title_ar: 'هوية التطبيق',
        title_en: 'App Identity',
        body_ar: 'غيّر اسم التطبيق والشعار. التغييرات تنعكس فوراً على الفواتير وشريط التنقل.',
        body_en: 'Change app name and logo. Changes reflect instantly on invoices and the navbar.',
        placement: 'bottom',
      },
      {
        id: 'settings_theme',
        target: '[data-help="settings-theme"]',
        title_ar: 'المظهر واللغة',
        title_en: 'Theme & Language',
        body_ar: 'بدّل بين الوضع الفاتح والداكن. اختر لغة الواجهة العربية أو الإنجليزية.',
        body_en: 'Toggle between light and dark mode. Choose Arabic or English interface.',
        placement: 'bottom',
      },
      {
        id: 'settings_backup',
        target: '[data-help="settings-backup"]',
        title_ar: 'النسخ الاحتياطي',
        title_en: 'Backup & Restore',
        body_ar: 'يمكنك إنشاء نسخة احتياطية أو استعادة ملف قاعدة بيانات من هذا القسم.',
        body_en: 'Create a backup or restore a database file from this section.',
        placement: 'top',
      },
    ],
    tooltips: {},
  },

  /* ── STOCK / INVENTORY ──────────────────────────── */
  stock_levels: {
    title_ar: 'مستويات المخزون',
    title_en: 'Stock Levels',
    steps: [
      {
        id: 'stock_status_filter',
        target: '[data-help="stock-status-filter"]',
        title_ar: 'فلتر الحالة',
        title_en: 'Status Filter',
        body_ar: 'فلتر بحالة المخزون: جيد / منخفض / نافد / زائد. انقر على أي حالة للتصفية.',
        body_en: 'Filter by stock status: OK / Low / Out / Over. Click any status to filter.',
        placement: 'bottom',
      },
      {
        id: 'stock_color_code',
        target: '[data-help="stock-color-code"]',
        title_ar: 'دلالة الألوان',
        title_en: 'Color Codes',
        body_ar: 'أحمر = نافد | برتقالي = منخفض | أزرق = زائد | أخضر = جيد.',
        body_en: 'Red = out | Orange = low | Blue = overstock | Green = OK.',
        placement: 'start',
      },
      {
        id: 'stock_quick_adjust',
        target: '[data-help="stock-quick-adjust"]',
        title_ar: 'تسوية سريعة',
        title_en: 'Quick Adjustment',
        body_ar: 'تسوية مخزون صنف واحد مباشرةً بدون الذهاب لصفحة التسوية الكاملة.',
        body_en: 'Adjust a single item stock directly without going to the full adjustment page.',
        placement: 'start',
      },
    ],
    tooltips: {},
  },

  /* ── SHIFT MANAGEMENT ───────────────────────────── */
  shift_history: {
    title_ar: 'سجل الورديات',
    title_en: 'Shift History',
    steps: [
      {
        id: 'shift_open_btn',
        target: '[data-help="shift-open-btn"]',
        title_ar: 'فتح وردية جديدة',
        title_en: 'Open New Shift',
        body_ar: 'افتح وردية قبل بدء البيع. أدخل رصيد النقد الافتتاحي للدقة.',
        body_en: 'Open a shift before selling. Enter opening cash balance for accuracy.',
        placement: 'bottom',
        highlight_type: 'glow',
      },
      {
        id: 'shift_discrepancy',
        target: '[data-help="shift-discrepancy"]',
        title_ar: 'عمود الفرق',
        title_en: 'Discrepancy Column',
        body_ar: 'فرق > الحد المسموح يظهر باللون الأحمر. راجع تقرير الكاشير للتفاصيل.',
        body_en: 'Discrepancy above threshold shows in red. Review cashier report for details.',
        placement: 'start',
      },
    ],
    tooltips: {},
  },
};
